### ISSUE TITLE
Special characters are escaped when output is piped

### ISSUE THREAD

**Issue by nichobi** [vishen/go-chromecast#103]
Noticed that the output of go-chromecast commands have recently changed when they are being piped. In previous versions I believe the output of these commands were the same. 
```sh
$ go-chromecast ls
INFO[0000] 1) device="Chromecast" device_name="sputnik" address="192.168.1.150:8009" uuid="REDACTED"
```

```sh
$ go-chromecast ls | cat
time="2021-04-12T16:02:40+02:00" level=info msg="1) device=\"Chromecast\" device_name=\"sputnik\" address=\"192.168.1.150:8009\" uuid=\"REDACTED\"\n"
```

Version: `INFO[0000] go-chromecast dev (master) 2021-04-12T14:05:56Z`

**Comment by vishen** [comment]
Hmm, this is unexpected but there was some recent changes to the logging so I wonder if this has caused this issue. I'll take a look.

**Comment by vishen** [comment]
This should be fixed now. I think the change of logger did something when detecting the output.
