### ISSUE TITLE
Can't disconnect from a broken connection

### ISSUE THREAD

**Issue by erdnaxeli** [vishen/go-chromecast#104]
When using the http server, the /disconnect endpoint always returns an error if we try to disconnect from a broken connection.

For example, I use /connect with an existing chromecast, then the connection breaks. Calling /disconnect returns a 500 with:
> unable to disconnect from device: use of closed network connection

The thing is that the code never calls `delete(h.apps, deviceUUID)` when there is an error, so the code think it is still connected and any command for this device will try to use this broken connection and will fail. Even if the device comes back later there is no way to talk to him again, you need to restart the http server.

Steps to reproduce:
* start the go-chromecast http server
* connect to an existing device: `GET /connect?uuid=XYZ`
* play a media on the chromecast
* run a seek-to command: `POST /seek-to?uuid=XYZ&seconds=200`
* **while the seek-to curl is still running**, drop the traffic: `iptables -A OUTPUT -d <chromecast's ip> -j DROP`
* the seek-to should then return an error: "unable to seek-to device: unable to write binary format: write tcp …: write: broken pip"
* disconnect: `POST /disconnect?uuid=XYZ` => error
* remove the iptable rule: `iptable -D OUTPUT -d <chromecast's ip> -j DROP`
* connect: `POST /connect?uuid=XYZ` => "device uuid is already connected"
* seek-to: `POST /seek-to?uuid=XYZ&seconds=200` => error

While doing that I got two different errors from the /disconnect endpoint:
* the first call returned "unable to disconnect from device: tls: failed to send closeNotify alert (but connection was closed anyway): write tcp …: write: broken pipe"
* then all calls returned "unable to disconnect from device: use of closed network connection"

The /disconnect should drop the connection on error, even if a proper disconnection failed, so we could later reconnect.

FYI this is related to https://github.com/erdnaxeli/castblock/issues/5.

**Comment by vishen** [comment]
Thank you for that @erdnaxeli. Feel free to reopen if it doesn't fix it.
