### ISSUE TITLE
Support Text To Speech

### ISSUE THREAD

**Issue by mattbucci** [vishen/go-chromecast#12]
@vishen for my use I would want something like this.

Would you accept a PR if I write one? let me know, if so I'll use Google Cloud Text to Speech instead of Abusing Google Translate.

**Comment by vishen** [comment]
I don't quite understand where you would use Text To Speech. Would it be something like `go-chromecast text-to-speech` and then it listens to what you say? Or are you meaning something else?

**Comment by mattbucci** [comment]
something like this `go-chromecast speak "Hi There, The Time is now 7:53AM." -n "Bedroom Speaker"` 

We then generate an MP3 of the text "Hi There, The Time is now 7:53AM." Leveraging https://cloud.google.com/text-to-speech/ and run go-chromecast load <mp3 we just generated> and google home reads the text aloud in the bedroom

**Comment by vishen** [comment]
Oh, that would be cool! I will happily accept a PR for that :)  If the text-to-speech api returned a url with the mp3 file, you can possibly use that as the content-url for the default application. But not sure what is possible.

**Comment by vishen** [comment]
I have merged an experimental text-to-speech support.
