### ISSUE TITLE
Does this program work with youtube urls?

### ISSUE THREAD

**Issue by gotbletu** [vishen/go-chromecast#127]
tried these commands, it opens the chromecast app on my TV but no video plays

```
go-chromecast load 'https://www.youtube.com/watch?v=abcde'
go-chromecast -d "SHIELD Android TV" load 'https://www.youtube.com/watch?v=abcde'
```

otherwise it works fine with my local mp4/webm files on my computer

**Comment by vishen** [comment]
Unfortunately not sorry. I created an issue a while ago to track this #4, but admittedly it has seen no progress.

**Comment by gotbletu** [comment]
oh ok, thanks for the reply

**Comment by lexybarton** [comment]
@gotbletu I have a oneliner for you.
I use go-chromecast in Windows Powershell together with yt-dlp to play a video (I the example below I have the url address coped in a clipboard). 

`go-chromecast.exe -a <targetchromecast-ip-address> -p <targetchromecast-port> load $(yt-dlp.exe -g $(get-clipboard) | select -First 1)`

The _yt-dlp.exe -g_ is command to list urls. As the result might be more then one url I just select the first one in the below in the pipeline. Resulting string is than used in the go-chromecast command.
