### ISSUE TITLE
Add support for cyrilic names

### ISSUE THREAD

**Issue by walking-octopus** [vishen/go-chromecast#133]
Currently, they look like gibberish or some Unicode escapes, but I can't find any way of decoding them.

**Comment by vishen** [comment]
Where abouts is this happening? Can you post some screenshots?

**Comment by walking-octopus** [comment]
Sorry for not providing an example. Here.
```
Found 5 cast dns entries, select one:
1) device="MIBOX4" device_name="\\208\\147\\208\\190\\209\\129\\209\\130\\208\\184\\208\\189\\208\\176\\209\\143: \\208\\162\\208\\146" address="192.168.0.131:8009" uuid="6bfc41811209a83ba31e5654c35fc5fd"
2) device="MIBOX4" device_name="\\208\\155\\208\\181\\208\\189\\208\\176: \\208\\162\\208\\146" address="192.168.0.115:8009" uuid="ff5adaa9a629ed8e506de50473a8977e"
3) device="MIBOX3" device_name="\\208\\161\\208\\191\\208\\190\\209\\128\\209\\130\\208\\183\\208\\176\\208\\187: \\208\\162\\208\\146" address="192.168.0.122:8009" uuid="b6249cecd319d44ce2d7245416e179a0"
4) device="Google Home Mini" device_name="\\208\\161\\209\\130\\208\\176\\209\\129: \\208\\154\\208\\190\\208\\187\\208\\190\\208\\189\\208\\186\\208\\176" address="192.168.0.116:8009" uuid="1311d80f11a96bb66e4ff13d293c1436"
5) device="MIBOX3" device_name="\\208\\162\\208\\181\\208\\187\\208\\181\\208\\178\\208\\184\\208\\183\\208\\190\\209\\128 \\208\\178 \\208\\179\\208\\190\\209\\129\\209\\130\\208\\181\\208\\178\\208\\190\\208\\188 \\208\\180\\208\\190\\208\\188\\208\\181" address="192.168.0.118:8009" uuid="905742615e8fe16eaff6b08a3f8b6e90"
```

**Comment by vishen** [comment]
I am unsure why this is happening. It looks like it might be coming from the chromecast as the bytes you posted. Are you able to run the same again but this time with `--debug` and post the output? Just trying to work out if it is coming from the chromecast coded already or go-chromecast / Go is doing something weird. I tested it out locally but I couldn't recreate this issue.

**Comment by walking-octopus** [comment]
Should I run `go-chromecast --debug ls`?

**Comment by vishen** [comment]
Yeah, if you don't mind?

**Comment by walking-octopus** [comment]
Ok. I just don't see the difference.
```
~$ go-chromecast --debug ls
1) device="Google Home Mini" device_name="\\208\\161\\209\\130\\208\\176\\209\\129: \\208\\154\\208\\190\\208\\187\\208\\190\\208\\189\\208\\186\\208\\176" address="192.168.0.116:8009" uuid="1311d80f11a96bb66e4ff13d293c1436"
2) device="MIBOX4" device_name="\\208\\155\\208\\181\\208\\189\\208\\176: \\208\\162\\208\\146" address="192.168.0.115:8009" uuid="ff5adaa9a629ed8e506de50473a8977e"
3) device="MIBOX3" device_name="\\208\\161\\208\\191\\208\\190\\209\\128\\209\\130\\208\\183\\208\\176\\208\\187: \\208\\162\\208\\146" address="192.168.0.122:8009" uuid="b6249cecd319d44ce2d7245416e179a0"
4) device="MIBOX4" device_name="\\208\\147\\208\\190\\209\\129\\209\\130\\208\\184\\208\\189\\208\\176\\209\\143: \\208\\162\\208\\146" address="192.168.0.131:8009" uuid="6bfc41811209a83ba31e5654c35fc5fd"
```

**Comment by vishen** [comment]
Apologies, I thought it would give some extra info. What should `\\208\\155\\208\\181\\208\\189\\208\\176: \\208\\162\\208\\146` decode to? Do you happen to recognise this encoding?

**Comment by walking-octopus** [comment]
I don't recognize this encoding but have found a likely relevant [StackOverflow question](https://stackoverflow.com/questions/24434550/decode-escaped-cyrillic-with-javascript). The Google Home's name should decode to  `Стас: Колонка`.

**Comment by vishen** [comment]
Thanks. I think that Stackoverflow question explains what is happening. Although I can't see an easy way to do this in Go. Will take a look to see if there is an easy way to decode this.

**Comment by walking-octopus** [comment]
It does look very similar, but I couldn't use the provided code sample to decode Google Home's name.

**Comment by vishen** [comment]
@walking-octopus I have maybe added a fix for this, if you get a chance would you be able to try using the latest master and seeing if that fixes the issue you are seeing? I don't have a good to test this on a device at the moment.

**Comment by walking-octopus** [comment]
Wow! It works perfectly. Thanks!

**Comment by vishen** [comment]
Ah awesome! Thanks for finding that Stackoverflow answer, had no idea where to start if I didn't have that :)
