### ISSUE TITLE
It seems the server doesn't decode utf8 names

### ISSUE THREAD

**Issue by walking-octopus** [vishen/go-chromecast#136]
Hi! Thanks for maintaining this project.
It seems the `go-chromecast httpserver` doesn't decode the utf8 names. Is it in purpose or an unreported bug? If that is by design, then how would I decode them in JS?

**Comment by vishen** [comment]
@walking-octopus is this issues supposed to be closed?

**Comment by walking-octopus** [comment]
Yes. I accidentally downloaded an older version. Building it from the source fixed it. Sorry for wasting your time.

**Comment by vishen** [comment]
Ah excellent! No worries at all :)
