### ISSUE TITLE
Feature Request: Playlist in text format

### ISSUE THREAD

**Issue by aphsa** [vishen/go-chromecast#157]
Could you add the option to provide a playlist file similar to mpv.

```sh
mpv -playlist=filelist.txt
```
The file list would contain a list of file(s) needed to be played in a sequence

**Comment by vishen** [comment]
This sounds like a good addition. I think this could be added to the [playlist](https://github.com/vishen/go-chromecast/blob/master/cmd/playlist.go) command. Currently if the `playlist` command gets an argument that isn't a directory it fails, but we should change this to check if it is a file, and if so then use that for the list of filenames to play.

**Comment by holiman** [comment]
I implemented this, more or less, in https://github.com/vishen/go-chromecast/pull/180. I can change it to be integrated with `playlist` instead ?

**Comment by vishen** [comment]
> I implemented this, more or less, in #180. I can change it to be integrated with `playlist` instead ?

I think it's fine to leave as is, this should solve the issue I believe. But feel free to reopen if needed @aphsa .
