### ISSUE TITLE
"error: no cast devices found on network" after upgrade from windows 10 to windows 11

### ISSUE THREAD

**Issue by mcarbonneaux** [vishen/go-chromecast#175]
after i've upgraded my windows 10 to 11, go-chromecast does not see anymore my chromecast in my network.
and return "error: no cast devices found on network".

i've disable firewall but not working...

**Comment by mcarbonneaux** [comment]
i found... when windows update, they disabled ipv6 on my pc... after reactivated, they reworked...

**Comment by vishen** [comment]
@mcarbonneaux thanks for posting your fix :)

**Comment by vishen** [comment]
The problem is that the Google Homes use mDNS to discover devices, so a multicast discovery message is sent out and we just listen for any responses. I'm not sure how we could surface any errors here, but I'm open to suggestions?
