### ISSUE TITLE
No effect with http volume post 

### ISSUE THREAD

**Issue by domizilt** [vishen/go-chromecast#185]
I started the http server with ./go-chromecast httpserver and connected it with 

http://192.168.0.2:8011/connect?uuid=a0c20331e9188265e041e48ecf771c1b

I load a stream with 
http://192.168.0.2:8011/load?uuid=a0c20331e9188265e041e48ecf771c1b&path=https://icecast.radiobremen.de/rb/bremeneins/live/mp3/128/stream.mp3&content_type=stream

and I hear the music on the right device. So far so good but I have no influence on the volume. I tried following post:

http://192.168.0.2:8011/volume?uuid=a0c20331e9188265e041e48ecf771c1b&volume=0.5

an got following response: 

{"level":0.28,"muted":false}

but the volume level didn't change. What did I wrong?

**Comment by vishen** [comment]
Does controlling the volume work when you try it as a cli: `go-chromecast level 0.5`? If it does work then there is a bug somewhere in the http server. But If that doesn't work, then some chromecast applications don't respect all the chromecast commands so there might not be much we can do there.

**Comment by domizilt** [comment]
./go-chromecast -n Party volume 0.2 funktioniert! (level 0.5 nicht... unbekannter Befehl)

**Comment by domizilt** [comment]
It seems that the code ignores the volume parameter and does not get past the r.Method == "GET" query in line 382. Even with wrong syntax or value for &volume=0.5 (e.g.: &volume=a) in it only returns the current value and no error message. 

Unfortunately my knowledge is not sufficient to correct this. But in my opinion it would probably be better to define a GET /volume_get.... and POST /volume_set.... parameters. 

Translated with DeepL.com (free version)

**Comment by vishen** [comment]
Thanks for tracking down! Can you confirm if you were doing a `POST` when calling `http://192.168.0.2:8011/volume?uuid=a0c20331e9188265e041e48ecf771c1b&volume=0.5` ?

**Comment by domizilt** [comment]
I'am sorry, but I have no knowligde how i can send a http command explicit as a POST. I only sent http://192.168.0.2:8011/volume?uuid=a0c20331e9188265e041e48ecf771c1b&volume=0.5 ? in a bowser address line. Could you explain me how the correct way or command is?

**Comment by domizilt** [comment]
OK, I read a little bit an created following form:

<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>POST-Anfrage mit Formular</title>
</head>
<body>
    <form id="postForm" method="post" action="http://192.168.0.2:8011/volume">
        <input type="hidden" name="uuid" value="a0c20331e9188265e041e48ecf771c1b">       
		<input type="hidden" name="volume" value="0.5">
        <button type="submit">POST-Anfrage senden</button>
    </form>
</body>
</html>

after sending it the result is:

missing 'uuid' in query params

When I change the Mothod to "GET" I got the same information with no effect on the volume of course:

{"level":0.18,"muted":false}

**Comment by domizilt** [comment]
ok, sorry for the hasty posts. I found out that following code works:

```
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>POST-Anfrage mit Formular</title>
</head>
<body>
    <form id="postForm" method="post" action="http://192.168.0.2:8011/volume?uuid=a0c20331e9188265e041e48ecf771c1b&volume=0.5">
        <button type="submit">POST-Anfrage senden</button>
    </form>
</body>
</html>

```

**Comment by vishen** [comment]
Currently the HTTP server provided is only for basic APIs, it doesn't have a browser component just yet. So you can interact with the `go-chromecast` HTTP server with curl from your command line, eg: `curl -XPOST http://192.168.0.2:8011/volume?uuid=a0c20331e9188265e041e48ecf771c1b&volume=0.5`. But trying to use the browser will only do GET commands. We would need to implement a frontend for the browser which the uses the HTTP server's API.

I'm going to close this as I believe it is working as expected. Please feel free to reopen if needed.
