### ISSUE TITLE
"go test" fails with go 1.23

### ISSUE THREAD

**Issue by zi3m5f** [vishen/go-chromecast#194]
```
# github.com/rogpeppe/go-internal/testscript
vendor/github.com/rogpeppe/go-internal/testscript/exe_go118.go:14:27: cannot use nopTestDeps{} (value of type nopTestDeps) as testing.testDeps value in argument to testing.MainStart: nopTestDeps does not implement testing.testDeps (missing method InitRuntimeCoverage)
FAIL    github.com/vishen/go-chromecast [build failed]
```

FYI:
The next NixOS/nixpkgs release 24.11 switches to go 1.23 which causes this package to fail.
We will use go 1.22 for now (NixOS/nixpkgs#353037).

**Comment by vishen** [comment]
I've upgraded `go-chromecast` to go 1.23.2 and I also upgraded github.com/rogpeppe/go-internal/testscript to the latest. Looks to be passing the tests now. I'm going to close this issue, but please do reopen if it doesn't fix the issue!
