### ISSUE TITLE
multicast DNS doesn't always work.

### ISSUE THREAD

**Issue by vishen** [vishen/go-chromecast#24]
When using my pixel-slate, multicast doesn't seem to work, possibly due to the way the network interfaces and configurations are set up, since everything runs in nested containers. It could also be firewall issues, not sure.

There should be an alternative to multicast dns for issues like this.

1. Add 'addr' as a flag to specify the address of the device to use
2. Take a cidr of the local network; eg: `192.168.0.0/24`, and attempt to TCP connect to all ips on port `8009` and see if we get a `PONG` response for our `PING` request.

**Comment by ziutek** [comment]
In my case (I have two chromecasts in local network) `ls` command sees nothing:

```
$ go-chromecast ls
Found 0 cast devices
````

Setting `mdns.QueryParam.Domain` back to "local" helps:

```
$ go-chromecast ls
Found 2 cast devices
1) device="Chromecast Audio" device_name="CCA" address="192.168.1.40:8009" status="" uuid="..."
2) device="Chromecast" device_name="TV" address="192.168.1.41:8009" status="" uuid="..."
```

**Comment by vishen** [comment]
I am unsure about why this even changed. Thank you for finding that. I have pushed the fix to master.

**Comment by vishen** [comment]
MDNS will now try and use the selected network interface https://github.com/vishen/go-chromecast/pull/60. This doesn't seem to fix the issue however.

**Comment by vishen** [comment]
This issue seems to be fixed for me after some networking changes done on the underlying OS of my Pixel Slate, I don't know what they changed but it appears to be working now.
