### ISSUE TITLE
Add --version switch

### ISSUE THREAD

**Issue by moritzheiber** [vishen/go-chromecast#28]
It would be fantastic if go-chromecast were to show me which version is installed when I e.g. run

```sh
$ go-chromecast --version
go-chromecast v0.0.9 (<maybe-git-hash-here>)
```

It will make installing and maintaining go-chromecast on systems a lot easier.

**Comment by vishen** [comment]
This should be working with the latest release `v0.0.11`.

```
$ go-chromecast --version
go-chromecast v0.0.11 (87a4ec6) 2019-07-07T12:03:39Z
```

**Comment by mheiber-tier** [comment]
@vishen It would appear the functionality got lost with 0.0.12 again .. ?

```
./go-chromecast --version
[...]
unknown flag: --version
```

**Comment by moritzheiber** [comment]
@vishen It would appear the functionality got lost with 0.0.12 again .. ?

```
$ ls -l
total 18328
-rwxr-xr-x 1 moe moe 13609152 Okt 13 19:53 go-chromecast
-rw-r--r-- 1 moe moe  5128682 Okt 13 19:53 go-chromecast_0.0.12_Linux_x86_64.tar.gz
-rw-r--r-- 1 moe moe    11353 Okt 13 19:50 LICENSE
-rw-r--r-- 1 moe moe     8993 Okt 13 19:50 README.md
```
```
./go-chromecast --version
[...]
unknown flag: --version
```

**Comment by vishen** [comment]
Hmm,my  apologies. Let me see if I can fix this again!

**Comment by vishen** [comment]
Haha yup! This should be working again in `v0.0.13`:

```
$ ./go-chromecast --version 
go-chromecast v0.0.13 (3c39494) 2019-10-22T20:44:40Z
```

and there is a test to hopefully catch this again!
