### ISSUE TITLE
status and volume always report 1.0 during playback

### ISSUE THREAD

**Issue by jmbromley** [vishen/go-chromecast#37]
The status and volume commands correctly report the volume when the device is Idle, but when the device is playing (at least for internet hosted files) they always report the volume as 1.0.

This only appears to be a cosmetic bug, using the volume command to set the volume of a playing stream works correctly, but still (incorrectly) reports a value of 1.0.

**Comment by vishen** [comment]
Hmm, that is odd! The volume is reported back from the chromecast I think, although it does look like it takes the volume from the last media status sent from the chromecast. Maybe the chromecast is returning multiple media status for some reason. Let me investigate more.

**Comment by vishen** [comment]
OK, it looks like the chromecast returns two different volume settings. One for the receiver and one for the media being played, and these don't appear to be the same. `go-chromecast` is setting the receiver volume but was reporting the media volume. It will now report the receiver volume.
