### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by psykzz** [vishen/go-chromecast#45]
Is it possible to include windows binaries in releases?
I understand things like `ffmpeg` might not be available, but it could always throw errors in thoses cases.

**Comment by vishen** [comment]
Yeah, I can include that. I'll update this issue when I have added the windows binaries to releases.

**Comment by vishen** [comment]
I have released a new release `v0.0.14` (https://github.com/vishen/go-chromecast/releases/tag/v0.0.14) which has windows binaries. I don't have a windows machine to test these out though sorry, so hopefully it work!
