### ISSUE TITLE
Question: continous image streaming

### ISSUE THREAD

**Issue by titpetric** [vishen/go-chromecast#49]
I've just opened a PR #48:

- allows you to stream file.jpg or http://..../file.jpg and other supported image links
- updated the application extension check to ignore the query string (`URL/file.jpg?...`)

The latter fix was done due to `--disable-cache` having no effect on the particular image that I was pushing. My work around was to push it with a timestamp, so it could update on demand:

~~~
$ while true; do ./go-chromecast load -v --disable-cache -d Chromecast http://192.168.0.2/video.jpg?$(date +%s) --detach ; done
using device name=Living Room TV addr=192.168.0.168 port=8009 uuid=6ebab571c01c10cc618218e23775d4f6
DEBU[0003] (1)sender-0 -> receiver-0 [urn:x-cast:com.google.cast.tp.connection]: {"type":"CONNECT","requestId":1}  package=cast
DEBU[0003] (2)sender-0 -> receiver-0 [urn:x-cast:com.google.cast.receiver]: {"type":"GET_STATUS","requestId":2}  package=cast
DEBU[0003] (2)sender-0 <- receiver-0 [urn:x-cast:com.google.cast.receiver]: {"requestId":2,"status":{"applications":[{"appId":"CC1AD845","displayName":"Default Media Receiver","iconUrl":"","isIdleScreen":false,"launchedFromCloud":false,"namespaces":[{"name":"urn:x-cast:com.google.cast.cac"},{"name":"urn:x-cast:com.google.cast.debugoverlay"},{"name":"urn:x-cast:com.google.cast.broadcast"},{"name":"urn:x-cast:com.google.cast.media"}],"sessionId":"8365cf22-f9f8-41bd-a8a8-8d4fc9254c59","statusText":"Default Media Receiver","transportId":"8365cf22-f9f8-41bd-a8a8-8d4fc9254c59"}],"userEq":{},"volume":{"controlType":"attenuation","level":1.0,"muted":false,"stepInterval":0.05000000074505806}},"type":"RECEIVER_STATUS"}  package=cast
DEBU[0003] (3)sender-0 -> 8365cf22-f9f8-41bd-a8a8-8d4fc9254c59 [urn:x-cast:com.google.cast.tp.connection]: {"type":"CONNECT","requestId":3}  package=cast
DEBU[0003] (4)sender-0 -> 8365cf22-f9f8-41bd-a8a8-8d4fc9254c59 [urn:x-cast:com.google.cast.media]: {"type":"GET_STATUS","requestId":4}  package=cast
DEBU[0003] (4)sender-0 <- 8365cf22-f9f8-41bd-a8a8-8d4fc9254c59 [urn:x-cast:com.google.cast.media]: {"type":"MEDIA_STATUS","status":[{"mediaSessionId":61,"playbackRate":1,"playerState":"PAUSED","currentTime":0,"supportedMediaCommands":274447,"volume":{"level":1,"muted":false},"activeTrackIds":[],"media":{"contentId":"http://192.168.0.2/video.jpg","contentType":"image/jpeg","streamType":"BUFFERED","duration":0,"metadata":{"MetadataType":0,"artist":"","title":"","subtitle":"","releaseDate":""},"mediaCategory":"IMAGE","tracks":[],"breakClips":[],"breaks":[]},"queueData":{"startIndex":0},"currentItemId":1,"items":[{"itemId":1,"media":{"contentId":"http://192.168.0.2/video.jpg","contentType":"image/jpeg","streamType":"BUFFERED","duration":0,"metadata":{"MetadataType":0,"artist":"","title":"","subtitle":"","releaseDate":""}},"autoplay":true,"orderId":0}],"repeatMode":"REPEAT_OFF"}],"requestId":4}  package=cast
DEBU[0003] (5)sender-0 -> 8365cf22-f9f8-41bd-a8a8-8d4fc9254c59 [urn:x-cast:com.google.cast.media]: {"type":"LOAD","requestId":5,"media":{"contentId":"http://192.168.0.2/video.jpg?1574891070","contentType":"image/jpeg","streamType":"BUFFERED","duration":0,"metadata":{"MetadataType":0,"artist":"","title":"","subtitle":"","images":null,"releaseDate":""}},"currentTime":0,"autoplay":true,"queueData":{"startIndex":0},"customData":null}  package=cast
~~~

The debug output is there as more of a curiosity, since every time I call `load`, I wanted to see what kind of exchange was going on with the Chromecast. The issue I was trying to pin point was, particularly, a screen flicker whenever the LOAD command was sent.

Coming to my question:

What would be the best way to provide continous image streaming to the chromecast, without causing a flicker? If I'm looking just at looping the `load` command with a pre-defined address (`-a chromecast-IP`), it seems it would be able to send frames at about 6fps+ or so, but this has the overhead of a process exec (it would probably be faster as a stand-alone command implemented in go).

I'm actively trying to:

- have low cpu usage (e.g. avoid `ffmpeg` completely)
- screencasting the active linux desktop session eats up about 1/4 cores (which is still way less than ffmpeg which takes about 65% just for encoding)

The framerate isn't super important for me (I can live with a poor framerate), but the flickr is what makes it super unusable. Besides loading a playlist with tens of thousands of pre-generated jpg URLs and figure out how fast a playlist can transition, what other options do I have? I haven't seen anything in the spec, which would allow me to push an item to the playlist, for example. Any hints are welcome.

**Comment by titpetric** [comment]
Possible approaches:

- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/chromecast-caf-receiver/cast.framework.d.ts#L88
- https://developers.google.com/cast/docs/reference/caf_receiver/cast.framework.QueueManager

Not sure of the particulars, as the queue manager isn't implemented in this package. But sort of what I need is there -> insertItems to push a new URL at the end of the playlist, and there seems to be functionality for removing items, and triggering item playback.

I would consider having 5 slots or so, and appending the last image, removing the first image and looping over that. Hopefully, the Chromecast will be smart enough to transition smoothly through them. Do you have some sort of more appropriate (network protocol) documentation reference I could look at? I mostly end up on Android/IOS/Javascript APIs...

**Comment by titpetric** [comment]
The V2 also has a queueInsertRequestData structure so i suspect there are just unimplemented QUEUE_INSERT etc. payloads which are effectively undocumented. How to proceed? Reverse engineer the CAF/V2 JS APIs? I'd hope this would be more open, but alas...

**Comment by vishen** [comment]
Unfortunately that was the same documentation I used, I didn't find anything good out there but the google caf_receiver was the best I could find. 

Alas, `go-chromecast` does implement a small subset the queue manager api for the `go-chromecast playlist` command https://github.com/vishen/go-chromecast/blob/138133190012797072b46702bf1b024559634f83/application/application.go#L593 and https://github.com/vishen/go-chromecast/blob/138133190012797072b46702bf1b024559634f83/cast/payload.go#L39

I was able to get a slideshow of sorts working using `go-chromecast playlist ~/folder-of-images --continue=false` and then running `go-chromecast next` in a separate shell although this still cause a small blackscreen for a second between images. You can get it to repeat the queue by making some manual changes:

```
--- a/application/application.go
+++ b/application/application.go
@@ -617,11 +617,12 @@ func (a *Application) QueueLoad(filenames []string, contentType string, transcod
        for i, mi := range mediaItems {
                items[i] = cast.QueueLoadItem{
                        Autoplay:         true,
-                       PlaybackDuration: 60,
+                       PlaybackDuration: 5,
                        Media: cast.MediaItem{
                                ContentId:   mi.contentURL,
                                StreamType:  "BUFFERED",
                                ContentType: mi.contentType,
+                               Duration:    10,
                        },
                }
        }
@@ -631,7 +632,7 @@ func (a *Application) QueueLoad(filenames []string, contentType string, transcod
                PayloadHeader: cast.QueueLoadHeader,
                CurrentTime:   0,
                StartIndex:    0,
-               RepeatMode:    "REPEAT_OFF",
+               RepeatMode:    "REPEAT_ALL",
                Items:         items,
        })
```

but I couldn't get the duration (how long an image shows) to work for an image even though the [documentation](https://developers.google.com/cast/docs/reference/caf_receiver/cast.framework.messages.QueueItem.html#playbackDuration) implies it should work?

The `playlist` command is not suitable for a slideshow, but it is probably a good starting point to add a new `go-chromecast slideshow` command. Happy to accept a PR, otherwise I will take a look this weekend :)

> The latter fix was done due to --disable-cache having no effect on the particular image that I was pushing.

I don't quite understand what you mean here?

**Comment by titpetric** [comment]
Maybe i am misunderstanding what disable-cache option does, but i had to
add a cache breaking parameter to force the chromecast to reload the image.
The fix was just to support the parameter/correctly detect the extension.

I’ll check back on the rest of your reply, need to find some time to play
around with it.

BR

**Comment by vishen** [comment]
I have added a `go-chromecast slideshow images/*.jpg` command, it might do what you were asking?

**Comment by titpetric** [comment]
I’m not sure, I may have explained poorly - I continuously update a single
jpeg. Think of a webcam (auto refresh), it could be refreshed often
(desktop cast with xwd/scrot), or just 1-2 per minute. If you implemented
QUEUE_INSERT/DELETE, then it may be what I need.

My ultimate goal is to use it for generated jpeg dashboards, if i could get
rid of the flickr with new queue request apis.

BR,
Tit

**Comment by vishen** [comment]
Ah sorry, I misunderstood what you meant! Implementing the QUEUE_INSERT/DELETE might solve your issue, but it would only work for images that are returned over http(s) (since you would need a server to serve up the image if it was local).

One option would be to have `go-chromecast` watch for new files in a folder and add those to the playlist as they are created / modified, although this wouldn't get rid of the flicker when changing between images and this is would likely be quite a bit of effort to implement.

Another option is to write a separate webserver that produces the webcam like stream of images over http(s). Then you can point the chromecast to stream whatever content is being generated by the webserver. You could use `go-chromecast` to point the chromecast to the webserver serving the stream of images, or if you write the webserver in Go you could use `go-chromecast` as a library and do it internally. You will need to make sure that the content-type passed to the chromecast is a video type (ie: video/mp4) for the chromecast to stream the content.

I am not sure this is something that will be built into `go-chromecast` but it could be a new project that uses `go-chromecast` api. I'll take a look over the weekend and see what is possible.

**Comment by titpetric** [comment]
Yeah, http/https works for me, I already produced a webserver in the LAN that provides the image. I don't think I have a nice way of producing a video/mp4 without resorting to mpeg however (but i suspect I could generate .ts chunks / m3u8 without ffmpeg). Just pushing QUEUE_* messages would work for me, but i'll check if i can generate the required video/mp4 from the jpg, without actually resorting to ffmpeg.

**Comment by vishen** [comment]
OK cool! We can add the QUEUE_* commands and restrict them to http(s) urls for now. 

Thinking about this again, have you tried using the slideshow command for the single image: `go-chromecast slideshow http://webserver/image.jpg`? This should add the image to the queue on repeat, so every time the chromecast queue loads the next item (which will always be the same item) it will try and load that image from the webserver (although I haven't tried this though).

**Comment by titpetric** [comment]
I haven't no, but pushing the same image url loads the cached one, so i
suspect the slideshow would be cached. I was thinking of just generating a
m3u or maybe even a m3u8 and putting jpg files in the chunklist to see if
that works. It would be bizarre if it did, but it would be exactly what I
want since the chunklist does support tagging each chunk with a duration,
so i could dynamically set the refresh/framerate. It's gonna be some time
when i manage to put this test together, priorities :/

**Comment by vishen** [comment]
Ah, it must be getting cached on the chromecast then. I'll try and verify
when I can.

I have never used m3u so I am unsure if that will work sorry. You can take
a look at the list of supported media formats for the chromecast default
receiver https://developers.google.com/cast/docs/media. I am unsure if any
of the can do what you suggest though.

**Comment by titpetric** [comment]
I did a few tests with slideshow:

1. it does not take url parameters (only Load does),
2. with the local image, it is cached on chromecast side,
3. I tried duplicating the QueueItems (len*2, index i*2, i*2+1) to see if having 2 items in the playlist would be better (no change).

Both 2/3 have had the same image blinking you'd get by consecutively calling LOAD, there isn't a smooth transition between images, but it does seem faster than LOAD (I'm assuming since it doesn't re-create the target app on QUEUE_UPDATE).

Still left to test if I can just produce a playlist/chunklist.m3u8 with jpegs or something.

**Comment by titpetric** [comment]
I'm gonna close and mark this as resolved. I'm considering this impossible without writing your own custom reciever on the chromecast side. Whatever they have for their ambient features obviously isn't enabled for casting. I'm not super excited about converting jpg into mpeg-ts chunks, but ideally that would be the best way forward- m3u8+ single b-frame mpeg-ts chunks. I'm not enthusiastic to bring ffmpeg into the mix due to it's high resource usage.
