### ISSUE TITLE
Add an ls command to list all devices

### ISSUE THREAD

**Issue by mattbucci** [vishen/go-chromecast#5]
Is it possible to add an ls command so that you can use `go-chromecast ls` to list all available devices?

**Comment by vishen** [comment]
Yup, this should be doable! I'll take a look at adding it in.

**Comment by vishen** [comment]
You should be able to do `go-chromecast ls` now and it _should_ list all the available devices. Let me know if it is missing something. I will close this issue, but feel free to reopen.
