### ISSUE TITLE
Request for new release

### ISSUE THREAD

**Issue by Sergio-P** [vishen/go-chromecast#57]
I've just downloaded the binary included in the latest release version but it seems to be outdated. Many of the features presented in the readme are missed like slideshow command and m3u8 support. Could you please provide a new release? I can't install go in the host machine so my only option is to use the binary.

**Comment by vishen** [comment]
My apologies, I have been a bit slack with the releases. I have released `v0.0.15` https://github.com/vishen/go-chromecast/releases/tag/v0.0.15
