### ISSUE TITLE
Can this code be compiled for an ARM cpu?

### ISSUE THREAD

**Issue by Ruizzie** [vishen/go-chromecast#65]
Hi there,

Go-Chromecast is an amazing tool to script Chromecast commands. 

I would love to be able to run it on my Synology NAS, which has a Marvell Kirkwood 88F6282 ARM processor. 

Unfortunately my knowledge of compiling for Linux is very limited. Would this code work on an ARM processor? Or does it necessarily need to be a 386 or AMD processor?

Thank you for your feedback and the great work.

**Comment by vishen** [comment]
It should theoretically work on any architecture I believe. I have this working on my raspberry pi which is using ARMv7 in this project https://github.com/vishen/raspberrypi-osmc-controller-chromecast#building-for-raspberry-pi

If you have `go` installed you can try and crosscompile it with:
```
GOOS=linux GOARCH=arm GOARM=7 go build -o go-chromecast
```

If you let me know the arch and arm values I can try and crosscompile it and add it to releases?

**Comment by vishen** [comment]
I have added some arm releases if you would like to check those out https://github.com/vishen/go-chromecast/releases/tag/v0.2.5
