### ISSUE TITLE
[feature] Add support for seeking to a specific timestamp

### ISSUE THREAD

**Issue by stephen304** [vishen/go-chromecast#68]
It seems that the only supported commands for seeking are relative to the current position in the media. I would like a command to skip to a specific timestamp.

The reason I want this ability is so that I can investigate adding support for sponsorblock, in essence having a daemon watch all chromecasts on LAN, look up sponsor / midroll timestamps via the sponsorskip database, and automatically skip ads on all local chromecasts.

I suspect that using the relative seek commands would provide a subpar experience since the watch command has a polling interval, so the daemon would need to estimate when the player reaches the start of the segment to skip, as well as potential delays sending the seek command could lead to seeking too far.

**Comment by vishen** [comment]
This seems like it should be possible to do. It won't work for live-streaming media, or media that is being transcoded by ffmpeg, but for the rest it should work. I'll take a look into this.

**Comment by stephen304** [comment]
Thanks! If possible, it would also be great to seek to a float, since sponsorblock + contributors submit timestamps with pretty high precision.

**Comment by vishen** [comment]
I have added a `seek-to <timestamp_float>` command to master. This seems to be working for me at the moment when trying out on Youtube, so hopefully it works for you! I will add this to a new release a bit later today.

**Comment by stephen304** [comment]
Thanks that should be perfect!
