### ISSUE TITLE
[feature] Display youtube video ID in status command

### ISSUE THREAD

**Issue by stephen304** [vishen/go-chromecast#69]
I'm not sure if this is possible, but it would be super convenient to be able to get the youtube video ID in the status command, since for now I intent on spamming that command repeatedly as a source of information for skipping sponsors via the sponsorblock api

**Comment by vishen** [comment]
The only id that seems to come through is the id from the url, eg: `https://www.youtube.com/watch?v=bVJ-mWWL7cE` the id is `bVJ-mWWL7cE`. I have added this id to the status command if it is a youtube video. Hopefully this is helpful? 

If not can you give me an example of a youtube url and it's id and I can maybe look at parsing the youtube url for any ids if they exist in there.

**Comment by stephen304** [comment]
That's exactly what I needed, thanks!
