### ISSUE TITLE
Could you provide (RESTful)API for other GUI programs to call

### ISSUE THREAD

**Issue by rexzhang** [vishen/go-chromecast#74]

**Comment by vishen** [comment]
This would be quite cool actually. We could expose the same commands as the command line. Is there anything else that should go into the HTTP endpoints?

**Comment by rexzhang** [comment]
daemon mode

api
- list devices
- select/connect device
- disconnect/release device
- load(and play)
- pause/unpause
- seek: +/-
- volume: get/set
- mute/unmute
- stop
- status/event history

**Comment by vishen** [comment]
Those seem like a good starting point. Let me take a look at turning these into HTTP API endpoints.

**Comment by vishen** [comment]
There is a new subcommand on master `go-chromecast httpserver` which provides the following API:

```
GET /devices
POST /connect?uuid=<device_uuid>&addr=<device_addr>&port=<device_port>
POST /disconnect?uuid=<device_uuid>
POST /disconnect-all
POST /status?uuid=<device_uuid>
POST /pause?uuid=<device_uuid>
POST /unpause?uuid=<device_uuid>
POST /mute?uuid=<device_uuid>
POST /unmute?uuid=<device_uuid>
POST /stop?uuid=<device_uuid>
GET /volume?uuid=<device_uuid>
POST /volume?uuid=<device_uuid>&volume=<float>
POST /rewind?uuid=<device_uuid>&seconds=<int>
POST /seek?uuid=<device_uuid>&seconds=<int>
POST /seek-to?uuid=<device_uuid>&seconds=<float>
POST /load?uuid=<device_uuid>&path=<filepath_or_url>&content_type=<string>
```

**Comment by rexzhang** [comment]
great! I will try later.

**Comment by gnur** [comment]
It's working great, but the headers return the wrong content-type, messing up tools like https://github.com/ducaale/ht that will not trigger json formatting in the response.

**Comment by vishen** [comment]
Apologies, that was an oversight. I will push a fix for this.

**Comment by vishen** [comment]
Pushed a fix for this to master, will add this to a new release shortly.

**Comment by vishen** [comment]
Closing this as I believe it is done. Feel free to reopen.
