### ISSUE TITLE
Create new release including httpserver

### ISSUE THREAD

**Issue by pascaladriaansen** [vishen/go-chromecast#84]
Hi!

I just installed the latest release on a Raspberry Pi (armv6) by following these directions 

> If using Linux: Download the latest release, unzip using tar -xzf go-chromecast.tar.gz, and install using sudo install ./go-chromecast /usr/bin/

Unfortunately, it seems that the latest release does not yet include the httpserver feature that was recently added. Could a new release/build be added that includes this feature?

Thanks!

**Comment by vishen** [comment]
Ah, yes sorry, I have been meaning to do this. I will get this done in the next couple of days :)

**Comment by vishen** [comment]
https://github.com/vishen/go-chromecast/releases/tag/v0.2.6 has been released which included the http server :)

**Comment by pascaladriaansen** [comment]
Awesome, thanks so much!
