### ISSUE TITLE
watch command hangs if chromecast goes offline

### ISSUE THREAD

**Issue by stephen304** [vishen/go-chromecast#85]
I noticed that if I reboot my chromecast, the watch command doesn't exit and it also doesn't find the chromecast again when it boots back up. The simplest thing would be to exit if the connection is lost, but if it were to auto reconnect, that would be really cool too.

```
unable to update cast application: unable to write binary format: write tcp 192.168.1.226:59588->192.168.1.82:8009: write: broken pipe
```

**Comment by vishen** [comment]
Ah yeah, this is something I have noticed recently as well unfortunately. I have been thinking a solution would be to attempt to rediscover the cast on the network up to 5 times the exit if we can't rediscover and reconnect, I have been trying something similar with a different project to see if it works: https://github.com/vishen/raspberrypi-osmc-controller-chromecast/blob/master/main.go#L103-L115. I'll look at making a similar to change to the `watch` command.

**Comment by vishen** [comment]
I have made a change to the `watch` command that will attempt to retry for a lost chromecast connection for 5 times and then exit if it can't reconnect. Feel free to reopen if this doesn't work as expected. I tested it out on a couple of my chromecast devices and it seems to work, but I may not have tested all possibilities.
