### ISSUE TITLE
[Feature Request] Option to enable status probing with interval during watch

### ISSUE THREAD

**Issue by stephen304** [vishen/go-chromecast#86]
In order to increase the performance of my castblock app, I want to switch from polling `go-chromecast status` (which uses a lot of cpu since I decided to use a bash loop...) to continuously processing output from a long-running `go-chromecast watch` process. I noticed that while I run `status`, the chromecast broadcasts a detailed status update that `watch` receives that includes all the information I need, so if there was a switch to trigger that periodically (such as -i for interval) then I could use that which should be a lot more performant.

Alternatively, if you added such a flag to adjust the interval for the regular `>> YouTube (PLAYING)`... output, then I could use that too if the youtube ID was added to the output as well as using floats for the time remaining numbers.

Would it be possible to do either of these?

**Comment by stephen304** [comment]
@vishen I took a shot at it myself, these changes seem to work well. I can prepare a PR if that helps.

* Added interval flag for watch subcommand
* Added contentID to output
* Added 2 decimal places to the progress seconds

```
--- a/cmd/watch.go
+++ b/cmd/watch.go
@@ -24,6 +24,8 @@ import (
        pb "github.com/vishen/go-chromecast/cast/proto"
 )
 
+var interval float32
+
 // watchCmd represents the watch command
 var watchCmd = &cobra.Command{
        Use:   "watch",
@@ -53,9 +55,13 @@ var watchCmd = &cobra.Command{
                                                md := castMedia.Media.Metadata
                                                metadata = fmt.Sprintf("title=%q, artist=%q", md.Title, md.Artist)
                                        }
-                                       fmt.Printf(">> %s (%s), %s, time remaining=%.0fs/%.0fs, volume=%0.2f, muted=%t\n", castApplication.DisplayName, castMedia.PlayerState, metadata, castMedia.CurrentTime, castMedia.Media.Duration, castVolume.Level, castVolume.Muted)
+                                       switch castMedia.Media.ContentType {
+                                       case "x-youtube/video":
+                                               metadata = fmt.Sprintf("id=\"%s\", %s", castMedia.Media.ContentId, metadata)
+                                       }
+                                       fmt.Printf(">> %s (%s), %s, time remaining=%.2fs/%.2fs, volume=%0.2f, muted=%t\n", castApplication.DisplayName, castMedia.PlayerState, metadata, castMedia.CurrentTime, castMedia.Media.Duration, castVolume.Level, castVolume.Muted)
                                }
-                               time.Sleep(time.Second * 10)
+                               time.Sleep(time.Millisecond * time.Duration(interval * 1000))
                        }
                }()
 
@@ -84,5 +90,6 @@ var watchCmd = &cobra.Command{
 }
 
 func init() {
+       watchCmd.Flags().Float32Var(&interval, "interval", 10, "interval between status poll in seconds")
        rootCmd.AddCommand(watchCmd)
 }

```

**Comment by vishen** [comment]
This sounds like an awesome idea, happy to accept a PR :) I have been thinking that maybe we could produce a json output for the watch command that might be easier to parse for something like this? We could output the same we do for the http server which is https://github.com/vishen/go-chromecast/blob/master/http/types.go#L18, and we can add any missing data you might need to that struct as well.

**Comment by stephen304** [comment]
Cool, I opened #87. Json output would also be pretty useful if you were thinking one status object per line, I can just throw it into jq to parse. I honestly haven't touched the http server at all.

**Comment by vishen** [comment]
Thanks! I will look at adding a way to output the status as json :)

**Comment by vishen** [comment]
> json output would also be pretty useful if you were thinking one status object per line

I have taken an attempt at this and will produce a single line of JSON output with the application, media and volume data per interval:

```
$ go-chromecast watch --output=json
{"application":{"appId":"E8C28D3C","displayName":"Backdrop","isIdleScreen":true,"sessionId":"135b820d-5947-4244-9719-a6ddbf15d3b9","statusText":"","transportId":"135b820d-5947-4244-9719-a6ddbf15d3b9"},"media":{"mediaSessionId":0,"playerState":"PLAYING","currentTime":0,"idleReason":"","volume":{"muted":false},"currentItemId":0,"loadingItemId":0,"media":{"contentId":"","contentType":"video/webm","streamType":"LIVE","duration":0,"metadata":{"MetadataType":0,"artist":"","title":"","subtitle":"","images":null,"releaseDate":""}}},"volume":{"muted":false}}
```
