### ISSUE TITLE
Fail to play stream 

### ISSUE THREAD

**Issue by areqq** [vishen/go-chromecast#96]
load fail if in url no .mp3 extension, but the url is OK.

./go-chromecast -a 1.1.1.23 -v load http://stream.rcs.revma.com/ypqt40u0x1zuv
DEBU[0000] (1)sender-0 -> receiver-0 [urn:x-cast:com.google.cast.tp.connection]: {"type":"CONNECT","requestId":1}  package=cast
DEBU[0000] (2)sender-0 -> receiver-0 [urn:x-cast:com.google.cast.receiver]: {"type":"GET_STATUS","requestId":2}  package=cast
DEBU[0000] (2)sender-0 <- receiver-0 [urn:x-cast:com.google.cast.receiver]: {"requestId":2,"status":{"applications":[{"appId":"CC1AD845","displayName":"Default Media Receiver","iconUrl":"","isIdleScreen":false,"launchedFromCloud":false,"namespaces":[{"name":"urn:x-cast:com.google.cast.cac"},{"name":"urn:x-cast:com.google.cast.debugoverlay"},{"name":"urn:x-cast:com.google.cast.broadcast"},{"name":"urn:x-cast:com.google.cast.media"}],"sessionId":"5db49612-aa4c-4ef3-b99d-44002bb9ac6d","statusText":"Default Media Receiver","transportId":"5db49612-aa4c-4ef3-b99d-44002bb9ac6d","universalAppId":"CC1AD845"}],"userEq":{},"volume":{"controlType":"attenuation","level":1.0,"muted":false,"stepInterval":0.05000000074505806}},"type":"RECEIVER_STATUS"}  package=cast
DEBU[0000] (3)sender-0 -> 5db49612-aa4c-4ef3-b99d-44002bb9ac6d [urn:x-cast:com.google.cast.tp.connection]: {"type":"CONNECT","requestId":3}  package=cast
DEBU[0000] (4)sender-0 -> 5db49612-aa4c-4ef3-b99d-44002bb9ac6d [urn:x-cast:com.google.cast.media]: {"type":"GET_STATUS","requestId":4}  package=cast
DEBU[0000] (4)sender-0 <- 5db49612-aa4c-4ef3-b99d-44002bb9ac6d [urn:x-cast:com.google.cast.media]: {"type":"MEDIA_STATUS","status":[{"mediaSessionId":1,"playbackRate":1,"playerState":"PLAYING","currentTime":883.308866,"supportedMediaCommands":274447,"volume":{"level":1,"muted":false},"activeTrackIds":[],"media":{"contentId":"https://an.cdn.eurozet.pl/ant-waw.mp3","streamType":"BUFFERED","contentType":"audio/mpeg","mediaCategory":"AUDIO","duration":null,"tracks":[{"trackId":1,"type":"AUDIO"}],"breakClips":[],"breaks":[]},"currentItemId":1,"items":[{"itemId":1,"media":{"contentId":"https://an.cdn.eurozet.pl/ant-waw.mp3","streamType":"BUFFERED","contentType":"audio/mpeg","mediaCategory":"AUDIO","duration":null},"autoplay":true,"customData":{},"orderId":0}],"repeatMode":"REPEAT_OFF"}],"requestId":4}  package=cast
unable to load media: unknown file extension ""

**Comment by vishen** [comment]
This seems like a bug. We try and determine the content type of the media file because the chromecast can't always work it out. In the case of a URL we do a HEAD request to try and work out the content type. However, if we can't work out the content type we should still send it to the chromecast in the hopes that it can work it out.

**Comment by vishen** [comment]
I have pushed a fix for this to master.

**Comment by areqq** [comment]
now works, thanks !
